import type { Metadata } from 'next'
import NavbarComponent from '../navbar/page'

export const metadata: Metadata = {
  title: 'Kauan Dev',
  description: 'Generated by create next app',
  manifest:'/manifest.webmenifest'
}

export default function Home() {
  // const t = useTranslations('presentation')
  return (
    <>
      <NavbarComponent></NavbarComponent>
    </>
  )
}



